version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: app_db
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - TZ='Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: app_nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: app_backend
    volumes:
      - ./src:/var/www/app
    depends_on:
      - db
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - TZ='Asia/Tokyo'
      - LANG=ja_JP.UTF-8  # PHPMyAdminの言語を日本語に設定
    ports:
      - 8080:80
    depends_on:
      - db

